### PR TITLE
[trust-dns-proto] abstract udpSocket

### PR DESCRIPTION
**Pull request by chunyingw**
- Abstract trust_dns_proto::UdpStream and related types
- Make tokio-udp as optional dependencies
- Run rustfmt on the files modifed
- Fix clippy errors

### CODE REVIEW

**Comment by bluejekyll** [comment]
This all looks great. I don't have any comments. I'm rerunning the Windows tests to see if those are just transient errors.

**Comment by chunyingw** [comment]
Thanks. I missed the part it failed the Windows tests. Does it look good now?

**Comment by bluejekyll** [comment]
Yeah. I think windows mio might have some issues. Not related to your change.

**Comment by bluejekyll** [comment]
And thanks for the PR!

**Pull request merged**
