### PR TITLE
Add mutable access to Message fields

### PR DESCRIPTION
**Pull request by leshow**
closes: #1117

### CODE REVIEW

**Comment by leshow** [comment]
I left the return type as `&mut Vec`, but a mutable slice is also an option, let me know if you have a preference.

**Comment by bluejekyll** [comment]
If you want to be able to insert new Records into the `answers` or other sections, then I think it needs to be a Vec, right? Otherwise you would be limited to changing existing entries, right?

**Comment by leshow** [comment]
The particular use case was modifying existing `Record`s in `answers`, so either type would work for me. I've left it as `&mut Vec` though which is the most "open" option, if you're okay with that change.

**Comment by bluejekyll** [comment]
The only concern to think about is that we are exposing the internal data structure of the Message. I think I'm ok with this, but I want to think about it for a little bit.

**Comment by bluejekyll** [comment]
Ok, let's merge this, as-is, can always revisit in the future.

**Comment by bluejekyll** [comment]
Thanks for the PR!

**Comment by leshow** [comment]
Thank you!

**Pull request merged**
