### PR TITLE
Minimal versions

### PR DESCRIPTION
**Pull request by mathstuf**
---
Needs releases of https://github.com/tokio-rs/tokio/pull/1764, https://github.com/sfackler/typed-headers/pull/6, and https://github.com/alexcrichton/socket2-rs/pull/46 first.

This also only gets `trust-dns-resolver` working under the `-Z minimal-versions` flag. More PRs will need to be filed for the other crates to also work, but I don't need them immediately and this hole is deep enough as it is :/ .

### CODE REVIEW

**Comment by bluejekyll** [comment]
Looks like a lot of breakage from this. Also, is there a CI job we can add for this?

**Comment by mathstuf** [comment]
Well, it's broken because the dependent PRs haven't had releases yet.

As for CI, yes there is, but you'll need to either use `rustup` rather than a plain base image or split the lockfile generation into a different step than the build and test. The workflow is:

```sh
cargo +nightly generate-lockfile -Z minimal-versions
cargo +$minver build --all --frozen
cargo +$minver test --frozen --no-run --all
cargo +$minver test --frozen
```

Combine the last 3 commands how you see fit. Toolchains prior to 1.36.0 do not like `--frozen` at the workspace level for the build (test is OK with it).

The `gitlab-ci` configuration I'm using can be seen here: https://gitlab.kitware.com/utils/rust-git-workarea/blob/master/.gitlab-ci.yml

**Comment by mathstuf** [comment]
I also have Cirrus CI scripts for minimal versions here: <https://github.com/mathstuf/rust-keyutils/blob/master/.cirrus.yml>. Though it should really actually build with the minimal compiler version.

**Comment by djc** [comment]
If you want to rebase this, I think the blockers have been fixed now (and main no longer depends on typed-headers).

**Comment by mathstuf** [comment]
Seems that `trust-dns-resolver` is OK now. I did find one for `bin` that needs it, but `trust-dns-https` has other crates that need updates for `minimal-versions`, so I stopped there.

**Pull request closed without merging**
