### PR TITLE
Make ServerFuture generic over T: RequestHandler

### PR DESCRIPTION
**Pull request by Antti**
This allows you to easily implement a DNS server with your own handler.

Also pass in the whole request to the handler function, as sometimes you might be interested in some other details of the request, like the originating IP address.

### CODE REVIEW

**Comment by bluejekyll** [comment]
fixes #47

**Comment by bluejekyll** [comment]
Thanks again for the PR! This is a great change.

**Comment by bluejekyll** [comment]
btw, I just thought about this. in UDP it's simple to spoof the src IP address. If you're planning to use the Request.src_addr for any form of auth, you should be careful about what it would be used for. I do have plans to fix up the TLS support so that some client auth information could be passed up from the connection. That would be authenticated, and therefor could be used for authorization.

Anyway, occurred to me after thinking about this change.

**Comment by Antti** [comment]
@bluejekyll fair point, I was not thinking of using this for any form of auth, my idea was to create a DNS server capable of returning hosts own IP address (this might be useful for some sort of service discovery when you can't easily determine host's ip address).

**Pull request merged**
