### PR TITLE
bump version to 0.19.2

### PR DESCRIPTION
**Pull request by bluejekyll**

### CODE REVIEW

**Comment by chunyingw** [comment]
Ben,

trust-dns-proto and trust-dns-resolver version 0.19.2 have been ported into Fuchsia officially, thanks!

**Comment by bluejekyll** [comment]
Awesome news!!!

**Comment by bluejekyll** [comment]
This makes me exceptionally happy.

As you have time, as perhaps part of the comparability test suite, we should make sure to get the APIs used by Fuschia into a test that would help us enforce that we don’t break the interface.

Congratulations on this!

**Comment by chunyingw** [comment]
Thank you. I am working on the dns crate based on trust-dns* and the resolver service now on Fuchsia. I will come back for the porting of DNSSEC features after that.

 I agree it's import to make sure the the APIs used by Fuchsia are not broken through setting up tests. I am not very clear what kind of tests should I create. If you have any advice, please let me know.

**Pull request merged**
