### PR TITLE
Clippy fixes

### PR DESCRIPTION
**Pull request by jonasbb**
This fixes some clippy warnings.
The first commit contains fixes which are machine applicable.
The second commit fixes a buffer sizing where min and max were switched leading to a constant size.
The last commit fixes a problem with the manual implementation of `PartialOrd`.

### CODE REVIEW

**Comment by bluejekyll** [comment]
Oh, I'm about to bump the minimum version to `1.42` I think that will allow matches at that point.

**Comment by jonasbb** [comment]
I ran `touch **.rs; cargo +nightly clippy --all --all-targets --all-features --fix -Z unstable-options` to auto apply fixes and then checked the other two with `touch **.rs; cargo +nightly clippy --all --all-targets --all-features -- -Aclippy::match_like_matches_macro`.

If you are bumping the minimum rust version then I will update the PR and also fix the rustfmt problems. `matches!` is indeed available in 1.42.

**Comment by bluejekyll** [comment]
Ah. You ran it on nightly, I generally only focus on stable clippy warnings.

**Comment by jonasbb** [comment]
I thought I saw some lints also on stable. Anyway, I checked the changes, and they all look sensible to me. I updated the PR to the now most recent `main` state.

**Comment by jonasbb** [comment]
The clippy test fails in 1.47.0 with https://rust-lang.github.io/rust-clippy/rust-1.47.0/index.html#same_item_push
I purposefully did not address that lint in this PR since I find the suggested way using `resize` quite weird since it then requires to calculate the new size instead of how many elements to add.
Maybe `extend` + `std::iter::repeat(_).take(_)` would work better.

**Comment by djc** [comment]
See https://github.com/bluejekyll/trust-dns/commit/d53381edda7e2c787789b4d5704724cc5f24199b.

**Comment by bluejekyll** [comment]
I jumped the gun on this and just cleaned things up in #1235. I should have worked with you on finishing up this PR, but I wanted to unblock a lot of the other test failures.

**Comment by jonasbb** [comment]
No problem. I'm just going to close this PR then.

**Pull request closed without merging**
