### PR TITLE
add NAPTR record type

### PR DESCRIPTION
**Pull request by bluejekyll**
fixes: #654 

This does not add any `additionals` processing in the server, nor does it add any direct support in the Resolver, those can be future features if desired.

### CODE REVIEW

**Comment by nhoyle** [comment]
Thanks for this. I'll give feedback once I have a chance to use it (though not expecting any issues).

**Comment by bluejekyll** [comment]
There are some improvements we can make in the resolver and server, for example processing additionals for the replacement record.

The spec makes it clean that can be an SRV, and I’m not sure how much extra work chaining to SRV will be (should be fine). Anyway, there are definitely options to improve some of the other components around this.

**Comment by nhoyle** [comment]
In the most frequently used cases, I would _expect_ the direct response to be comprised of SRV recrods (see RFC 3263 if you really want gory details). Direct A/AAAA record responses are kind of a degenerate fallback. Automatically chaining the SRV values into the A/AAAA values as "additional" records would be a great feature, but isn't completely needed; the client can always launch a subsequent query for those.

**Comment by bluejekyll** [comment]
Ok. I opened #735, if you want to add any details. I’m worried that the resolver would create wasteful queries on resolution since it doesn’t know if it’s SRV or A/AAAA that needs to be resolved.

**Pull request merged**
