### PR TITLE
always attempt reconnect when nameserver is picked

### PR DESCRIPTION
**Pull request by bluejekyll**
Currently the NameServerPool can be exhausted when connections are not reattempted. This should make sure that connects will always be attempted even if all the connections are failed.

fixes: #454

### CODE REVIEW

**Comment by bluejekyll** [comment]
@sintanial, it you can, it would be great if you could test out this change.

**Comment by bluejekyll** [comment]
FYI @briansmith , you may be interested in this patch. This is to make the resolver more resilient to upstream NameServer connectivity issues.

Here are the changes:

- to always attempt to reconnect to name servers in case of a failure, before it would wait for a period of time before attempting a connection again.
- switching from a BinaryHeap, to a sorted Vec (I'm considering using SmallVec here in the Future) in the NameServerPool. This allows us to have a sorted view over the entire set of NameServers (usually ~2).
- To clone the sorted view of the NameServerPool (sorted lowest priority to highest) and then using that as a stack, to loop over all NameServers in an attempt to guarantee a result, in the face of connectivity issues.

**Comment by bluejekyll** [comment]
FYI @fafhrd91, while I don't have a test for the issue, that you mentioned at meetup, I reviewed the code around that error to try and understand what might have been going on. I think this patch should make us much more resilient to any NameServer connectivity issues.

**Comment by fafhrd91** [comment]
Hey, thanks! I’ll test and get back

**Comment by bluejekyll** [comment]
> Hey, thanks! I’ll test and get back

master has been updated to move to the new `tokio` and off `tokio-core`, not sure if that effects you.

**Comment by fafhrd91** [comment]
no, I will migrate to tokio in next version

**Comment by bluejekyll** [comment]
Because this is a logic change, I'm not sure about backporting this to 0.8, but we could discuss it.

**Comment by sintanial** [comment]
Ok i will test it maybe now, or tomorrow, i promise

**Comment by sintanial** [comment]
@bluejekyll i try to test this pull request, but i have some problem.
In my fork (https://github.com/sintanial/trust-dns) i merged 2 branches: 
1. https://github.com/bluejekyll/trust-dns/tree/fix-send-sync - because i need to use tokio::spawn()
2. https://github.com/bluejekyll/trust-dns/tree/fix-no-nameservers - for testing this case

after i try to use dns_resolver and catch panic, this is trace log 
[trusttest.log](https://github.com/bluejekyll/trust-dns/files/1998576/trusttest.log)

this is my code example (to use my version of trust_dns_resolver, you can pass in Cargo.toml
```trust-dns-resolver = { version = "0.8.1", git = "https://github.com/sintanial/trust-dns", branch = "master" }``` )
```rust
extern crate env_logger;
extern crate futures;
#[macro_use]
extern crate log;
extern crate tokio;
extern crate tokio_io;
extern crate trust_dns_resolver;

use futures::{Future, Stream};
use futures::sync::mpsc;
use futures::sync::oneshot;
use std::io;
use std::net::SocketAddr;
use tokio::runtime::Runtime;
use trust_dns_resolver::config::{ResolverConfig, ResolverOpts};
use trust_dns_resolver::ResolverFuture;

fn main() {
    env_logger::init();

    let (close_tx, close_rx) = oneshot::channel();
    let (mut runtime, sender) = run_trust_dns_resolver(close_rx);

    let (receiver_tx, receiver_rx) = oneshot::channel();

    sender.unbounded_send(("www.kinopoisk.ru".to_string(), 80, receiver_tx));

    let process = receiver_rx.then(|res| {
        println!("resolve result: {:?}", res);
        Ok(())
    });

    runtime.spawn(process);
    runtime.shutdown_on_idle().wait().unwrap();
}

pub fn run_trust_dns_resolver(close_rx: oneshot::Receiver<()>) -> (Runtime, mpsc::UnboundedSender<(String, u16, oneshot::Sender<io::Result<Vec<SocketAddr>>>)>) {
    let mut runtime = Runtime::new().unwrap();

    let (resolve_task_tx, resolve_task_rx) = mpsc::unbounded();

    let handler = runtime.executor();

    let resolver = ResolverFuture::new(ResolverConfig::default(), ResolverOpts::default());

    let resolver_process = resolver
        .map_err(|err| io::Error::new(io::ErrorKind::Other, "failed to create resolver"))
        .and_then(move |resolver| {
            let resolve_process = resolve_task_rx
                .map_err(|()| io::ErrorKind::UnexpectedEof.into())
                .for_each(move |(host, port, responser): (String, u16, oneshot::Sender<io::Result<Vec<SocketAddr>>>)| {
                    debug!("[trust-dns] try resolve host: {:?}", host);
                    let resolve_process = resolver
                        .lookup_ip(&host[..])
                        .then(move |res| {
                            match res {
                                Ok(lookup) => {
                                    let mut res = Vec::new();
                                    for addr in lookup.iter() {
                                        res.push(SocketAddr::new(addr, port));
                                    }

                                    responser.send(Ok(res))
                                }
                                Err(err) => responser.send(Err(io::Error::new(io::ErrorKind::Other, format!("failed to resolve dns; host={:?}, err={}", host, err)))),
                            };
                            Ok(())
                        });

                    handler.spawn(resolve_process);

                    Ok(())
                });

            let close_process = close_rx.then(move |res| {
                debug!("[trust-dns] receive close signal;");
                res
            }).map_err(|err| io::Error::new(io::ErrorKind::Other, err));

            let process = resolve_process.select(close_process).map(|ok| ok.0).map_err(|er| er.0);

            process
        });

    runtime.spawn(resolver_process.map_err(|_| ()));
    info!("[trust-dns] complete resolver;");

    (runtime, resolve_task_tx)
}
```

**Comment by bluejekyll** [comment]
That’s a new one. Thanks for trying it out. I’ll probably merge the Send/Sync PR before this one. Clearly some more testing is needed.

**Comment by sintanial** [comment]
I think it's panic, because https://github.com/bluejekyll/trust-dns/blob/fix-send-sync/resolver/src/lookup_state.rs#L36 thread_local. 
So in this line https://github.com/bluejekyll/trust-dns/blob/0.8_release/resolver/src/lookup_state.rs#L64 increased count in one thread, but https://github.com/bluejekyll/trust-dns/blob/0.8_release/resolver/src/lookup_state.rs#L101 this code can executed in another thread, where QUERY_DEPTH=0

**Comment by bluejekyll** [comment]
Ah. I’ve needed to fix that query depth param. Thanks for tracking that down!

**Comment by sintanial** [comment]
Your welcome. I have tried to fix this bug, but i am new in rust, so it's very difficult to me now, sorry ... )

**Comment by bluejekyll** [comment]
Thank you, but don’t worry about it. This feature is improperly implemented. I need to apply a better solution that doesn’t assume a single threaded implementation. It will require a few changes.

**Comment by bluejekyll** [comment]
Ok, the patch for the query depth issue is in #460. I’m going to merge that, and then this.

**Comment by sintanial** [comment]
Cool, i will test it tomorrow ;)

**Comment by sintanial** [comment]
@bluejekyll so i try to test it and receive same panic !
```
DEBUG 2018-05-15T08:51:13Z: monkeyrust::proto::dns: [trust-dns-resolver] try resolve host: www.kinopoisk.ru
thread 'tokio-runtime-worker-2' panicked at 'attempt to subtract with overflow', /Users/test/.cargo/git/checkouts/trust-dns-9db67f484c5d170b/0484b74/resolver/src/lookup_state.rs:113:38
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
so ```task_local! {static QUERY_DEPTH: RefCell<u8> = RefCell::new(0)}``` did not solve the problem

**Pull request merged**
