### PR TITLE
upgrade trust-dns-proto to edition 2018

### PR DESCRIPTION
**Pull request by chunyingw**
- Upgrade trust-dns-proto to rust edition 2018
- Remove unused "mut" in some places

### CODE REVIEW

**Comment by bluejekyll** [comment]
@chunyingw, there are quite a few failures with this at the moment, I assume you noticed that?

**Comment by chunyingw** [comment]
Hey Ben,

I did not notice until this morning. Thanks for the reminder. I will work
on the fix tomorrow.

Chunying

**Comment by bluejekyll** [comment]
Ok. No rush on my part. Just wanted to make sure you were aware. Thanks!

**Comment by chunyingw** [comment]
Hey Ben,

Sorry for the noise. With the 10 commits, it seems good now? Any comments?

**Comment by chunyingw** [comment]
It did not pass codecov check. Any advice on that?

**Comment by bluejekyll** [comment]
Don’t worry about the code coverage. Your hitting such a wide area of code that you are getting an error related to some older stuff with less coverage.

**Comment by bluejekyll** [comment]
It looks like there are some merge conflicts, could you rebase your changes on master?

**Comment by chunyingw** [comment]
I am a little confused. I see the last commit #50bcc41already merge the upstream master #3500bb88.
Could you say more about the merge conflicts? Where do you see it?

**Comment by bluejekyll** [comment]
This is the current message I see from Github: "This branch cannot be rebased due to conflicts", so not sure. Are you not seeing any merge requirements locally?

**Comment by chunyingw** [comment]
Thanks. Out of curiosity, did you any operation on your side to solve the
issue?

**Comment by bluejekyll** [comment]
No, Github wouldn't allow a rebase and merge (which is what I usually do), but would allow a squash and merge.

I like to have all PR changes come into master at the same time, as opposed to a merge without rebase. Squash is always an acceptable option, and probably makes more sense in this case anyway since the numerous commits don't add a ton for historical reference.

Thanks again for the PR, really appreciate your work on this!

**Pull request merged**
