### PR TITLE
Port away from tokio_core::reactor::Core

### LINKED ISSUE #385: Port to tokio
tokio-core is being replaced with tokio. Is there any plan to port trust-dns in the near future?

### PR DESCRIPTION
**Pull request by Keruspe**
Fixes #385 
Based on #440 

Everything but server and integration-tests is ported

Let's see what the CI has to say

### CODE REVIEW

**Comment by Keruspe** [comment]
Some code formatting changes are due to prior iteration of these patches.
I'm currently fixing that and will force-push a new version. Hopefully it'll confirm that this PR makes the appveyor timeout go away :)

**Comment by bluejekyll** [comment]
Awesome work! let me know when you feel this is ready.

**Comment by Keruspe** [comment]
I still see some issues for the server and the integration-tests ports, once those are fixed, I think this will be good to go

**Comment by bluejekyll** [comment]
And this will cover #440 as well, right?

**Comment by Keruspe** [comment]
Everything now seems to work properly.
Some things might need to be lazier to have a more intuitive usage but all the tests pass and there is no longer any tokio-core dependency (apart from transitive ones form tokio-tls and tokio-openssl)

**Comment by bluejekyll** [comment]
Awesome work! This has been a slog I realize. Great job, and thank you!

**Comment by bluejekyll** [comment]
Merging! thank you @Keruspe !

**Pull request merged**
