### PR TITLE
Implement EDNS Client Subnet ECS reading and writing

### PR DESCRIPTION
**Pull request by mokeyish**
https://www.rfc-editor.org/rfc/rfc7871#section-6

### CODE REVIEW

**Review by bluejekyll — APPROVED** [review]
This looks good to me. Thanks for contributing!

**Comment by mokeyish** [comment]
Do you have a better name for ECS?  It seems that it is not appropriate to name ECS.

**Comment by bluejekyll** [comment]
> Do you have a better name for ECS? It seems that it is not appropriate to name ECS.

You could call it "ClientSubnet" if you're referring to the field. That seems like it would be a better name (the EDNS of ECS, EDNS Client Subnet would be redundant).

Another question I have is if we might want to store or at least have conversions with the IpNet type? We already have this dependency in the library: https://docs.rs/ipnet/2.7.1/ipnet/enum.IpNet.html

**Comment by mokeyish** [comment]
I have tried `ipnet`，but not satisfy  all derived traits.

**Comment by bluejekyll** [comment]
This looks good. Merging, thanks for the PR!

**Pull request merged**
