### PR TITLE
Resolver

### PR DESCRIPTION
**Pull request by chunyingw**
WIP
For trust-dns-resolver crate itself, `cargo build && cargo test` works. I will work on the other crates that will be impacted by the abstraction. Meanwhile I will wait for `update to tokio 0.2 release` to be merged.

### CODE REVIEW

**Comment by bluejekyll** [comment]
FYI, I think we want to wait on this, I'm currently cleaning up all the spawns in the Resolver, and trying to make the Spawner generic such that something like fuschia could more easily swap out these components...

**Comment by chunyingw** [comment]
Sure, no problem.
Any rough idea about the ETA?

**Comment by bluejekyll** [comment]
I'm hoping to have a rebased version of #935 off of master by end of day today... we'll see.

**Comment by chunyingw** [comment]
Cool!

**Comment by bluejekyll** [comment]
@chunyingw can we close this? I'm guessing it's no longer needed?

**Comment by chunyingw** [comment]
Yes please close it.

**Pull request closed without merging**
