### PR TITLE
Pass DnsRequestOptions to DNSSEC validating routines

### PR DESCRIPTION
**Pull request by wiktor-k**
Hello,

This PR fixes the issue reported in #1735 and makes sure that the `DnsRequestOptions` that the client specifies are being forwarded to the DNSSEC validating functions.

The change is basically grabbing a copy of the options (because request is passed by value to `send` the original options cannot be used) and then adding the options parameter to `validate_*` functions and using that instead of `DnsRequestOptions::default()`. The additional parameter should not affect public API since all these functions are not marked `pub`.

When this PR gets merged I'll follow up with the "configurable max_request_depth" PR that doesn't make sense if the options are not being forwarded in the first place :).

Suggestions welcome! :wave:

### CODE REVIEW

**Review by djc — COMMENTED** [review]
This mostly looks good to me. It looks like a bunch of functions are taking a `&DnsRequestOptions` only to dereference it when using. If we're just going to dereference it anyway, why not take ownership? The mix between passing references and owned values seems confusing.

**Comment by wiktor-k** [comment]
Good idea, I'll fix that and re-submit. Thanks!

**Review by djc — APPROVED** [review]

**Comment by wiktor-k** [comment]
I've adjusted the code. With your suggestions applied it looks cleaner. I couldn't avoid all explicit dereferences since [`options()` returns a ref in `DnsRequest`](https://github.com/bluejekyll/trust-dns/blob/main/crates/proto/src/xfer/dns_request.rs#L46) but I don't think this is a big issue.

**Comment by wiktor-k** [comment]
Sorry for the noise @bluejekyll but what's the workflow for getting an approved PRs merged in here? I'm wondering if I can be of help in here...

**Comment by djc** [comment]
Hey, sorry for the slow feedback cycle here. I often like to get an additional review from @bluejekyll before a PR is merged, but he is currently on vacation. In the absence of his review, this is straightforward enough that I'll just merge it now.

**Comment by wiktor-k** [comment]
Ah, no worries. I asked because I've got yet another PR I planned to submit that depends on this one...

Thanks for the quick response and have a nice day! :wave:

**Pull request merged**
