### PR TITLE
Mark ForwardLookup as public

### PR DESCRIPTION
**Pull request by chotchki**
I am trying to implement a wrapper around ForwardAuthority so I can intercept for rewriting/auditing what a dns forwarder produces. However implementing a wrapper is extremely challenging without ForwardLookup also being public.

### CODE REVIEW

**Comment by chotchki** [comment]
> This looks good, though will need some minimal documentation to pass our clippy lints: https://github.com/bluejekyll/trust-dns/runs/7019222106?check_suite_focus=true

Added what I think the structure is supposed to do as a doc comment. 

cargo clippy && cargo check && cargo test all passed cleanly!

**Comment by chotchki** [comment]
I think I collided with your OpenSSL upgrade, I'll fetch and re-push once #1728 finishes.

**Review by bluejekyll — APPROVED** [review]
Looks good. Thanks for the PR!

**Comment by bluejekyll** [comment]
> I think I collided with your OpenSSL upgrade, I'll fetch and re-push once #1728 finishes.

this should be good now if you want to rebase.

**Comment by bluejekyll** [comment]
Looks like something got a little funky on the commits. I’ll take a look tomorrow.

**Comment by chotchki** [comment]
I'm going to close this and remake, I found other tweaks to visibility I need so I'll make a clean branch off main and manually reapply before I open a new pull request.

**Pull request closed without merging**
