### PR TITLE
👌 Add cargo audit to the test matrix

### PR DESCRIPTION
**Pull request by ChristianWitts**
Signed-off-by: Christian Witts <cwitts@gmail.com>

### CODE REVIEW

**Comment by bluejekyll** [comment]
Hm, I'm not sure why, but check seems to be failing:

```text
    Checking trust-dns-openssl v0.4.0-alpha.1 (file:///home/travis/build/bluejekyll/trust-dns/openssl)
error[E0599]: no method named `set_verify_cert_store` found for type `&mut openssl::ssl::SslConnectorBuilder` in the current scope
  --> openssl/src/tls_stream.rs:97:14
   |
97 |             .set_verify_cert_store(store.build())
   |              ^^^^^^^^^^^^^^^^^^^^^
```

I haven't been able to repro this error.

**Comment by ChristianWitts** [comment]
Apologies for taking so long to respond @bluejekyll, I have fixed the issue (it requires the OpenSSL deb installation), so the build should be green now.

**Comment by bluejekyll** [comment]
Excellent. thanks for following up.

**Comment by bluejekyll** [comment]
Thanks for the PR @ChristianWitts! This is a great addition to the maintenance of the library.

**Pull request merged**
