### PR TITLE
 resolver: Refactor `LookupFuture` to remove `task::current().notify()`. 

### PR DESCRIPTION
**Pull request by hawkw**
Depends on #480.

This is essentially the same set of changes as #480 but applied to 
`lookup::LookupFuture`. I thought it was good for these similar futures to be
implemented in a consistent style.

Potentially, I think there is some code that's common between `LookupIpFuture`
and `LookupFuture` that could be factored out; I haven't yet come up with a 
way to do this that doesn't introduce _more_ complexity, but I'm sure it'sa
possible.

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

### CODE REVIEW

**Comment by bluejekyll** [comment]
Just waiting for tests to pass. Thanks again for showing me this pattern! I really wish I’d seen it before.

**Comment by hawkw** [comment]
@bluejekyll my pleasure! Once again, the "loop trick", as far as I can tell, is originally due to @carllerche, I just copied it from him :)

**Comment by hawkw** [comment]
Looks like the red :x: is from codecov due to insufficient patch coverage (but the patch _increases_ project coverage by 0.03% 🤷‍♀️); is that a blocker?

**Comment by bluejekyll** [comment]
No. I was just in the air. Merging now that I’m landed ;)

I need to fix the codecov targets.

**Comment by bluejekyll** [comment]
Gah. GitHub is being funky on my phone. I’ll merge in a little bit.

**Comment by bluejekyll** [comment]
ok, had to do that one manually...

**Comment by hawkw** [comment]
No worries, thanks for getting it merged! GitHub on mobile is sometimes difficult...

**Pull request merged**
