### PR TITLE
1445 Replace all min & max constructs with clamp

### PR DESCRIPTION
**Pull request by chrismiceli**
replace .max().min() constructs with .clamp()

----

fixes: #1445

### CODE REVIEW

**Comment by djc** [comment]
I'm guessing this might require an MSRV bump? Otherwise I'm all for it.

**Comment by bluejekyll** [comment]
Yup, we need to bump the rustc version to `1.50.0` for this. If you search for `1.46.0`, there should be changes to READMEs and the Makefile.toml. Change those locations to `1.50.0`. Once that change is made, the tests should pass, and then we can merge.

Thanks for the PR!

**Comment by djc** [comment]
@bluejekyll hmm, are your sure this trade-off is worth it? I'd rather keep the MSRV down a little bit so as to stay compatible with the tokio ecosystem (6 months), and the benefit of doing this now doesn't seem that great.

**Comment by bluejekyll** [comment]
oh, that's an interesting point... has Tokio been discussing increasing their min version?

We've discussed briefly in the past our stance on MSRV... I'm ok, with a Tokio ecosystem litmus for that.

**Comment by djc** [comment]
I think they stick to feature releases upholding a 6-month old MSRV (currently still 1.45).

**Comment by chrismiceli** [comment]
I can update the MSRV in this pull request, and then keep it open for a few months, or should we just close this and reopen when appropriate?

**Comment by chrismiceli** [comment]
> 
> 
> I can update the MSRV in this pull request, and then keep it open for a few months, or should we just close this and reopen when appropriate?

I went ahead and submitted the change just for feedback, even for crates that don't use clamp.

**Comment by bluejekyll** [comment]
Thank you! I think we can just leave this open with the note that we’ll be waiting until Tokio is on 1.50.

**Comment by bluejekyll** [comment]
Going through some older PR's. I think we're up to 1.54 now, so we can bring this forward. @chrismiceli , if you have time to rebase this (I think the changes to the MSRV in the README's can just be removed from the PR).

If you don't, I'll find some time soon.

**Comment by chrismiceli** [comment]
> Going through some older PR's. I think we're up to 1.54 now, so we can bring this forward. @chrismiceli , if you have time to rebase this (I think the changes to the MSRV in the README's can just be removed from the PR).
> 
> If you don't, I'll find some time soon.

Let me try this tonight and report back.

**Review by bluejekyll — APPROVED** [review]
Looks great, thanks for finishing this up!

**Pull request merged**
