### PR TITLE
Take the current header truncated bit into account

### PR DESCRIPTION
**Pull request by ilaidlaw**
We deserialize a message, examine the contents, and re-serialize it. We noticed that the new serialized message was missing the `truncate` bit. This patch fixes it in our case, but not sure if this is the correct approach in general. Welcome for feedback and suggestions on a different fix!

### CODE REVIEW

**Comment by bluejekyll** [comment]
Thanks for the PR.

If I remember this code correctly, the reason it was here is during traction by the server. Have you tested this locally to see if it is working as you expect?

Are you constructing a truncated request by hand?

**Comment by ilaidlaw** [comment]
Yes we've added a test in our project which takes a response with the truncate bit set, then de-serializes into a Message, re-serializes and verifies the truncate bit is still set.

**Comment by djc** [comment]
It would be good to make sure we have test coverage for that in the trust-dns test suite, as well.

**Comment by ilaidlaw** [comment]
I tweaked the tests to use the truncate flag, let me know if that is sufficient.

**Comment by bluejekyll** [comment]
Thanks for the PR, merging. The cleanliness failure will be fixed OOB.

**Pull request merged**
