### PR TITLE
Separate default `rustls::ClientConfig` for each protocol

### LINKED ISSUE #1990: DoQ default configuration is invalid
Currently DoT, DoH and DoQ share the same `ClientConfig`:
https://github.com/bluejekyll/trust-dns/blob/bf04bc8d3efec41d29cf558416b3dbed2d26ae02/crates/resolver/src/tls/dns_over_rustls.rs#L30-L56

All three implementations can't share the same configuration as they differ on some properties:
- **ALPN** (mandatory)
  - DoT: None
  - DoH: "h2" (current)
  - DoQ: "doq"
- **SNI** (optional)
  We probably want to continue disable SNI for DoT by default (though the only public server that I found supporting DoQ, AdGuard, requires SNI for both DoQ and DoT), but disabling SNI for DoH by default is strange.

The fast fix is probably easy, just use a different `ClientConfig` for each protocol. This does have a big downside though, when using multiple backends this will parse the root certificates multiple times.

This in turn could be solved by using [`WebPkiVerifier`](https://docs.rs/rustls/0.21.5/rustls/client/struct.WebPkiVerifier.html), but that would require `dangerous_configuration` and I'm not sure if we want to use that because it would activate it for upstream users as well.

So unless we are fine with activating `dangerous_configuration`, this would probably require some fix in Rustls. Considering @djc maintains both, I'm gonna hold back from creating an issue there until further feedback.

### PR DESCRIPTION
**Pull request by daxpedda**
This PR separates the default configuration used by each protocol to allow correct default ALPN and SNI configuration. 

The certificates provided by `webpki-roots` are parsed only once, the `ClientConfig` is cloned and then modified for each protocol. The clone doesn't actually clone the certificates, as they are stored in an `Arc<WebPkiVerifier>`, which avoids re-parsing the certificates over and over again but more importantly doesn't multiply the memory usage for each cloned `ClientConfig`.

See #1990 for more details on the issue addressed here.

Based on #1943.
Fixes #1990.

### CODE REVIEW

**Comment by bluejekyll** [comment]
@daxpedda, does this change supercede #1943? i.e. that one is not relevant after this?

**Comment by daxpedda** [comment]
> @daxpedda, does this change supercede #1943? i.e. that one is not relevant after this?

It's based on #1943, so it includes it, yes.
Considering we now have #2005, this PR doesn't make a whole lot of sense right now until we figure that out.

**Comment by djc** [comment]
Is there any code actually depending on serde capabilities and/or `Copy`? Could you do a separate PR to see what it looks like to remove these? Maybe look at `git blame` to see when/why they were added?

**Comment by daxpedda** [comment]
This is the original issue adding Serde support to `ResolverOpts`: https://github.com/bluejekyll/trust-dns/issues/490.
Removing `Copy` is a bit annoying because now we have to clone it everywhere, but it's not a big deal considering it's all `Arc`s and what-not.

`trust-dns-server` relies on it though, it uses Serde to be able to store and load the config. If you go all the way down [`ForwardConfig`](https://github.com/bluejekyll/trust-dns/blob/272059870a12e49fdd0286506f0d32582871018e/crates/server/src/store/forwarder/config.rs#L12) is the one using `ResolverOpts`, which bubbles up until it reaches [`trust_dns_server::Config`](https://github.com/bluejekyll/trust-dns/blob/272059870a12e49fdd0286506f0d32582871018e/crates/server/src/config/mod.rs#L38).

Here is me playing around with the idea: https://github.com/bluejekyll/trust-dns/compare/main...daxpedda:trust-dns:resolver-opts-copy-serde-test.

**Comment by djc** [comment]
@bluejekyll what do you think? I'm inclined to think that the complete reflection of `ResolverOpts` via the `ForwarderConfig` is probably not very load-bearing, and it seems to make sense to store TLS configs in the `ResolverOpts` instead of as process-wide `static`s.

**Comment by daxpedda** [comment]
I also made a branch only removing `Copy`. We could then use `serde(skip)` and document that `ResolverOpts` just doesn't de/serialize TLS configurations and inserts the default instead.

**Comment by djc** [comment]
> I also made a branch only removing `Copy`. We could then use `serde(skip)` and document that `ResolverOpts` just doesn't de/serialize TLS configurations and inserts the default instead.
> 
> [2720598...daxpedda:trust-dns:resolver-opts-remove-copy](https://github.com/bluejekyll/trust-dns/compare/2720598...daxpedda:trust-dns:resolver-opts-remove-copy)

That sounds like a good path forward, let's do that in a separate PR as a first step?

**Comment by daxpedda** [comment]
Closing in favor of #2031.

**Pull request closed without merging**
