### PR TITLE
remove the direct dependency to quinn-udp

### PR DESCRIPTION
**Pull request by zh-jq**
The cargo.lock file is also updated

### CODE REVIEW

**Review by djc — COMMENTED** [review]
We should actually just remove this dependency -- #1916 switched to using the `quinn::udp` re-export instead, so we no longer need to depend on this directly.

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
What was your reason to update the `Cargo.lock` file, other than just propagating the quinn-udp removal? It seems odd to me that some dependencies were removed in #1930 only to be added back here.

**Comment by zh-jq** [comment]
> 

The file is auto updated by cargo update, and the CI passed by only downgrading time crates, so is there any reason to keep an old cargo.lock?

**Comment by bluejekyll** [comment]
If it passes the MSRV checks and all the other tests, I'm ok with the update to the lock file personally... that's really just a check for people to know all the versions which the project has tested against and are known to be "good".

**Comment by zh-jq** [comment]
> that's really just a check for people to know all the versions which the project has tested against and are known to be "good".

I restored the old Cargo.lock file now. But I don't think this will make sense for library users.

**Comment by djc** [comment]
> I restored the old Cargo.lock file now. But I don't think this will make sense for library users.

Library users aren't affected by the `Cargo.lock` file, at all, so there's no need to do anything for their use cases.

> If it passes the MSRV checks and all the other tests, I'm ok with the update to the lock file personally... that's really just a check for people to know all the versions which the project has tested against and are known to be "good".

If this was the policy, we could have random `Cargo.lock` updates in every PR. IMO that would make changes harder to review, so I prefer to deal with lockfile updates separately from other changes.

**Comment by bluejekyll** [comment]
Thanks, @djc we can set a policy for Cargo.lock updates being separate. I think we could at that to CONTRIBUTING, I’ll try and find some time to add that explicitly in there.

**Review by bluejekyll — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
