### PR TITLE
Cleanups to dependencies (split futures) and modernize style

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by djc** [comment]
I think this failure is spurious.

**Comment by bluejekyll** [comment]
Yes, it looks like the new retry didn't completely resolve the test issue.

**Comment by djc** [comment]
> Yes, it looks like the new retry didn't completely resolve the test issue.

What do you mean? I'm confused.

**Review by bluejekyll — APPROVED** [review]
Wow, you are a force of nature! This is a huge cleanup, thank you!

**Comment by bluejekyll** [comment]
>>> I think this failure is spurious.

>> Yes, it looks like the new retry didn't completely resolve the test issue.

> What do you mean? I'm confused.

I thought you were talking about the https test failing again?

**Comment by djc** [comment]
@bluejekyll can you merge this? I don't have permissions to bypass failing tests.

**Comment by bluejekyll** [comment]
Will do. Those failures look like environment issues?

**Comment by djc** [comment]
I guess? Not sure.

**Pull request merged**
