### PR TITLE
add rustfmt to CI

### PR DESCRIPTION
**Pull request by little-dude**
This PR add a rustfmt job that fails when the code is not formatted with rustfmt.
Fix https://github.com/bluejekyll/trust-dns/issues/293

### CODE REVIEW

**Comment by bluejekyll** [comment]
Thanks for the PR!

**Comment by little-dude** [comment]
I'll add a commit with the rusfmt changes later. I first want to make sure the build fails if rustfmt was not run.
Also, notice that the rustfmt config changes the `try!` into `?`

**Comment by little-dude** [comment]
example of failure due to rustfmt: https://travis-ci.org/bluejekyll/trust-dns/builds/307284347

**Comment by bluejekyll** [comment]
Looks great! Thanks for all of this. That's a huge change, took me a while to look through all the diffs.

let me know if you're done with this, and I'll merge in.

**Comment by little-dude** [comment]
> Let me know if you're done with this, and I'll merge in.

I'm done :)

> one question, does this rustfmt match the version shipping with the rls?

I really don't know about this. All I know is `rustfmt-nightly` is the [branch that is under active development](https://www.ncameron.org/blog/rustfmt-changes/).

**Comment by bluejekyll** [comment]
ok, I think i'd like to make this an allowed failure. rustfmt-nightly just failed to compile for me (needed to update my rustc nightly version) ;)

Then we'll see how it goes. Would you mind making that change?

**Comment by little-dude** [comment]
Sure, we can still make it a non-allowed failure when rustfmt works on stable.
Feel free to squash when merging, I preferred didn't re-write the history to avoid confusion when reviewing.

**Comment by bluejekyll** [comment]
Thanks, this is a great change. Really appreciate all the work to cleanup the code.

**Pull request merged**
