### PR TITLE
Borrow `Handle`s, don't consume them

### PR DESCRIPTION
**Pull request by rushmorem**
Fixes https://github.com/bluejekyll/trust-dns/issues/167

### CODE REVIEW

**Comment by bluejekyll** [comment]
Hmm. I noticed on twitter that there have been some problems downloading the rust installers on appveyor. Looks like this might have triggered that.

**Comment by bluejekyll** [comment]
https://github.com/rust-lang-nursery/rand/commit/bb78689

**Comment by bluejekyll** [comment]
http://help.appveyor.com/discussions/problems/7115-curl-cant-download-files-through-ssl#comment_43044339

**Comment by bluejekyll** [comment]
This looks good to me. Once tests are passing I'll merge in. Thanks for the PR!

**Comment by rushmorem** [comment]
> This looks good to me. Once tests are passing I'll merge in.

I'm monitoring the tests to make sure that I didn't miss anything. Unfortunately, I don't have any Windows box to test this on so I was counting on AppVeyor, which unfortunately, is failing to download some files as you have already noticed.

**Comment by rushmorem** [comment]
Travis is passing but before you merge, let me try to employ that temporary workaround and see if we can get AppVeyor to work as well.

**Comment by rushmorem** [comment]
After employing the AppVeyor workaround, all tests are now passing. Since the AppVeyor images will be fixed today, do you want me to remove the workaround or leave it in place?

**Comment by bluejekyll** [comment]
It's fine for now I think. Mind creating an issue? We can remove it later.

**Comment by rushmorem** [comment]
> Mind creating an issue? We can remove it later.

Done. See https://github.com/bluejekyll/trust-dns/issues/169.

**Comment by bluejekyll** [comment]
Excellent! Thanks again for the PR!

**Comment by rushmorem** [comment]
It's the least I could do. Thanks for this wonderful crate :)

**Pull request merged**
