### PR TITLE
add non_exhaustive to public enums

### PR DESCRIPTION
**Pull request by bluejekyll**
I don't know if we want to make this guarantee. But It's worth putting it up for discussion.

We know that record types will be coming in the future, but adding non_exhaustive to RecordType is also a bit annoying because the RecordTypes are mostly fixed. So The question here is, where do we want to add non_exhaustive such that minor and patch releases are forward compatible. Do we want to make forward compatibility a guarantee on perhaps on patch releases, but not minor releases? See #1425, which happened on a pre 1.0 patch release as an example.

How extreme do we want to be on this at the detriment of losing one of Rusts greatest checks (all enum variants are covered in a match statement).

Fixes:  #1425

### CODE REVIEW

**Comment by djc** [comment]
In my opinion, semver compatibility trumps the ability to exhaustively match enums. The contract that semver-compatible versions should just compile is widely upheld, and we should not mess with it. The clippy lint seems like a fine solution for those who really want to make sure they match every variant.

**Comment by bluejekyll** [comment]
ok, let me clean this up and get it ready.

**Comment by bluejekyll** [comment]
Ok @djc I think this is ready, unless you see something missing.

**Comment by bluejekyll** [comment]
@djc any concerns with me merging this?

**Comment by djc** [comment]
I can review it tomorrow.

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
Nice work!

**Pull request merged**
