### PR TITLE
Make message round trip for fuzzing

### PR DESCRIPTION
**Pull request by bluejekyll**
@saethlin, I'm finally picking this back up. I restructured the directories in your fuzz layout, but otherwise this directly copies your work in #1606

closes: #1606
closes: #1605
Fixes: #1571
Fixes: #1570

### CODE REVIEW

**Comment by bluejekyll** [comment]
@saethlin, maybe you could provide some guidance here, this ran fine up until this point:

```text
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ProtoError { kind: DomainNameTooLong(256) }', fuzz/fuzz_targets/message.rs:12:39
```

I can provide the corpus, but it doesn't take too long to trigger this. That is a valid error, and it's getting triggered during serialization, which is vaguely correct. So I think it means we're not validating the name length on parsing the data. Would you agree with that?

**Comment by saethlin** [comment]
I think you just found https://github.com/bluejekyll/trust-dns/issues/1570

**Comment by bluejekyll** [comment]
I added a patch. Ok, we now have a problem with CSYNC, so I'll open an issue for that, but ignoring that type, I just ran this for 5 minutes without issue.

**Comment by bluejekyll** [comment]
FYI, @djc, any concerns with merging this?

**Comment by djc** [comment]
I quickly skimmed it and it seems okay. I'm a little confused about the difference between `data()` and `rdata()`.

**Comment by bluejekyll** [comment]
@djc, I deprecated `rdata()` because it was hiding the fact that `data` in the record is actually Optional. It made a problem for things like roundtripping, etc. So `data()` will return `Option<RData>` instead of masking that with a `RData::Zero` type.

I think this is better, more Rust standard, but if you disagree we can find another way.

**Comment by bluejekyll** [comment]
@djc once we merge this, it will fix the cleanliness target. Then I can merge #1629 and I think we're ready for another alpha release.

**Review by djc — APPROVED** [review]

**Pull request merged**
