### PR TITLE
update tokio following RustSec advisory

### PR DESCRIPTION
**Pull request by trinity-1686a**
see https://rustsec.org/advisories/RUSTSEC-2021-0072

### CODE REVIEW

**Comment by djc** [comment]
Given that we don't even call `JoinHandle::abort()` and given that the new tokio release is semver-compatible with the releases depend on, I'm not sure this is useful.

If we want to force downstream users to use latest tokio, we should also update the dependency specifications for all of our crates to pick up newer tokio. In most cases downstream users will pick up newer tokio anyway when they install or upgrade trust-dns.

**Comment by trinity-1686a** [comment]
this is mostly not useful. `Cargo.lock` only affect binaries, not lib-crates. The goal is mainly to make `cargo audit` happy, and I tend to prefer this to adding an exception.

**Comment by bluejekyll** [comment]
I agree with trinity on this. Easiest path to a clean audit, right?

**Comment by djc** [comment]
Fair enough.

**Review by djc — APPROVED** [review]

**Pull request merged**
