### PR TITLE
fix truncation promotion to TCP

### PR DESCRIPTION
**Pull request by bluejekyll**
fixes: #1627 

I verified this with the example in #1627. Clearly we have a gap in testing, I want to track that down and add or fix the test case for this.

FYI, @peterthejohnston

### CODE REVIEW

**Comment by peterthejohnston** [comment]
Thanks for tagging me -- I think I see what's going on. A response with no records with the `truncated` flag set was considered an error, and this meant it wasn't retried over TCP, because it looks like we only consider `truncated` in the case of an OK response: https://github.com/bluejekyll/trust-dns/blob/main/crates/resolver/src/name_server/name_server_pool.rs#L230

I think the first arm of that match should be more like:
```
            let udp_res = match Self::try_send(opts, datagram_conns, request).await {
                response if response.truncated() => {
                    debug!("truncated response received, retrying over TCP");
                    response
                }
                ...
            };

```
So that we always retry a `truncated` response over TCP, regardless of if it's considered an error or not.

I could check if this fixes the reported issue sometime later today, and if it does I'm happy to write up a test case covering this.

**Comment by bluejekyll** [comment]
Yeah, the recognition of "error" in this context is complex. With the patch I put in, it fixes the specific issue, we'll see what happens with the tests. I think one issue is that we don't pass back the response message on errors, so we don't have the ability to check for truncation on Errors. We could change the Errors to optionally include a Message (if it exists), and that would probably make things generally better.

I'm not sure if that would create other issues...

**Comment by bluejekyll** [comment]
One thing I noticed is that between the 0.20 branch and this, your improvements on error handling make the response to truncated message much faster. So overall, your past changes look to really improve the resolver experience, which is nice to see.

**Comment by bluejekyll** [comment]
> I'm wondering whether a truncated response is semantically considered an "error" or not in the RFCs. 

It is not an "error" according to the RFCs, the responses comes through as `NoError`. If I have some time, I'm going to try and preproduce the original issue with a test, and add it to this PR.

**Comment by bluejekyll** [comment]
So we did have a test for this case, it just so happened that due to some copy-pasta, it never properly checked that truncation occurred properly.

I fixed the test, verified that it fails in main, and then promoted it. I think we might have a gap where if the UDP message is truncated *and* contains answers, then we will not promote to TCP. I think we might want to always promote to TCP if the truncated flag is set on the response...

**Comment by bluejekyll** [comment]
Ok, and I figured out why that test was passing in main as it was, vs the new tests.

In order to trigger the bug in #1627, there needed to be an empty answer from the UDP request. The test case actually had records in the UDP response, so the code path that had the issue was working the an `Ok` in the `name_server_pool`, properly saw that it was a truncated response, promoted to TCP and got the correct record. The change to the test to break it had an empty UDP response, which in `main` caused the code path to work off an `Err` which caused the request to fail and never promote to TCP.

With the new test and the old test having an empty UDP response, we now have better coverage on the truncated response code to TCP. We might want to refactor the code to be a little less brittle, but I'm happy that we now have proper coverage for all this area of code.

**Pull request merged**
