### PR TITLE
OpenSSL 3.0 compliant

### PR DESCRIPTION
**Pull request by HLFH**
This PR https://github.com/bluejekyll/trust-dns/pull/1840 can be cancelled/closed.

My PR https://github.com/bluejekyll/trust-dns/pull/1841 could either:
 - supersede the PR https://github.com/bluejekyll/trust-dns/pull/1839 because it fully fixes the issues with OpenSSL 3.0.
 - or it could be rebased after this PR https://github.com/bluejekyll/trust-dns/pull/1839 is either merged or split into two commits 1) core changes 2) formatting/structure/documentation and merged.

### CODE REVIEW

**Comment by HLFH** [comment]
Comments:

OPENSSL=/usr/local/opt/openssl/bin/openssl ==> this is the correct PATH on macOS
OPENSSL=/usr/bin/openssl ==> this is the correct PATH on Arch Linux and most of other GNU/Linux distributions.
I think we we should support at least two paths based on if the script `scripts/gen_certs.sh` is being run on macOS or `GNU/Linux`.

**Comment by bluejekyll** [comment]
If this fixes the issues currently, we can merge this in.

**Comment by bluejekyll** [comment]
It looks like bind may not be compiling properly now. Might need to bump the version there. I'm going to merge this as is, and disable the compatibility test suite for now.

**Review by bluejekyll — APPROVED** [review]
Thank you for cleaning this up and making it all work with OpenSSL 3.0.

**Comment by HLFH** [comment]
> It looks like bind may not be compiling properly now. Might need to bump the version there. I'm going to merge this as is, and disable the compatibility test suite for now.

Fixed by PR https://github.com/bluejekyll/trust-dns/pull/1846.

**Comment by darnuria** [comment]
Just for history purpose! No problem it's fine! thanks. ^_^

**Pull request merged**
