### PR TITLE
Populate name_pointers correctly via MessageResponseBuilder request

### PR DESCRIPTION
**Pull request by jeff-hiner**
Works around https://github.com/bluejekyll/trust-dns/issues/1743 for single queries, which should cover most standard cases.

### CODE REVIEW

**Comment by djc** [comment]
Would you mind splitting this into two commits, splitting out the field rename? I'm not very familiar with this code and splitting it up would help me review it.

**Comment by jeff-hiner** [comment]
Sure, I guess? The name `original` isn't very useful, so I had figured the rename would make it easier to review what's going on.

**Comment by jeff-hiner** [comment]
Alright, I've split it up. Hope that helps!

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
It seems okay. @bluejekyll please give this another look when you're back?

**Pull request merged**
