### PR TITLE
upgrade to rusqlite 0.26.2

### PR DESCRIPTION
**Pull request by bluejekyll**

### CODE REVIEW

**Comment by djc** [comment]
They've issued a v0.26.3 release that reverts to 2018 edition.

**Comment by bluejekyll** [comment]
Yeah. I noticed that. I’m going to drop this from the backward compatibility tests once I have a moment.

**Comment by bluejekyll** [comment]
I’m tempted to file an issue with them, but I’m not sure if long-term we’re going to have this as a dependency.

**Comment by djc** [comment]
File an issue about what?

**Comment by djc** [comment]
I do agree it might make sense to drop the sqlite server backend, it seems too opinionated (of necessity) to be generally useful.

**Comment by bluejekyll** [comment]
I meant file an issue with rusqlite folks about upgrading the language version, and yanking the previous version, in a minor release. Feels a little wrong.

**Comment by bluejekyll** [comment]
@djc, any concerns with this?

**Comment by bluejekyll** [comment]
I'm going to unblock other changes and get this in.

**Pull request merged**
