### PR TITLE
Server async

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by bluejekyll** [comment]
I'll take a look through this today. Do you recommend going through each commit?

**Comment by djc** [comment]
Yup, that's pretty much true for any of my PRs.

**Review by bluejekyll — APPROVED** [review]
I went through this, it all looks really good. Should make future refactorings easier as this is all simpler now. Thanks for doing this!

**Comment by bluejekyll** [comment]
Just going to let the tests run, and then will merge.

**Pull request merged**
