### PR TITLE
Improved doc example for async client usage

### PR DESCRIPTION
**Pull request by ErwanDL**
This is the first PR associated with #1532 (sorry for the delay). It replaces the existing async client example with what I hope is an improved example, making use of the async/await syntax and using the `#[tokio::main]` macro, which should make it even easier to understand for newcomers. I also choose to setup a TCP connection in this example instead of UDP, so that both options are covered by different examples.

### CODE REVIEW

**Comment by bluejekyll** [comment]
using the `tokio::main` in the docs will require a bit of a wrapper around the doctest I think, since we don't have tokio enabled across all features.

If it fails, i'll post back a reference for how to do that. Thanks for taking the time to come back and submit this!

**Comment by ErwanDL** [comment]
It seems the doctests are still passing according to the CI, right ? I'm not sure why the code coverage went down though, as I didn't add nor remove any actual code.

**Review by bluejekyll — APPROVED** [review]
looks great, thank you!

**Comment by bluejekyll** [comment]
Yeah, we don't need to worry about the coverage...

Thanks for getting this in.

**Pull request merged**
