### PR TITLE
upgrade rusqlite to avoid future compatibility problem

### PR DESCRIPTION
**Pull request by hdhoang**
due to rust-lang/rust#49799

Compatibility note: with 0.14, rusqlite's result count type is now usize. I have chosen to cast it to i32 instead of changing `WrongInsertCount`, since it's a public type.

Should I also add a note to upgrade to usize when trust-dns-server bump major version? Or should I make the switch right away (it seems 0.15 is already in the work)?

### CODE REVIEW

**Comment by bluejekyll** [comment]
Yes, let’s just make the error carry a u32. That’s fine.

Will this break existing builds? I might need to backport it to the 0.14 branch.

0.15 is being worked on now, basically waiting on my slow moving HTTS integration.

**Comment by hdhoang** [comment]
I have switched over to `usize`, but I have no idea about the existing builds.

Also, this closes #550. That looks like a nice bot.

**Comment by hdhoang** [comment]
slproweb has moved on to openssl 1.1.0i. You can bump it up or I'll take care of that in another PR.

**Comment by bluejekyll** [comment]
Yeah. I like that bot.

**Comment by bluejekyll** [comment]
Thanks a lot for the patch! Merged.

**Pull request merged**
