### PR TITLE
Add resolver.clear_cache() sync and async

### PR DESCRIPTION
**Pull request by dns2utf8**
Hi all

This is the first PR to address the network change issue #1608

I am currently not sure what is smarter:
a. dropping the resolver in the consuming application on a network change or
b. reloading the settings in this crate

Cheers,
Stefan

### CODE REVIEW

**Review by djc — APPROVED** [review]
LGTM!

**Comment by dns2utf8** [comment]
This just occurred to me: Should we call it `flush_cache` or `clear_cache`?

**Comment by djc** [comment]
I think `clear()` fits better with Rust collection APIs; flush may be more familiar with users of DNS, but I think the former is probably more appropriate here.

**Comment by dns2utf8** [comment]
Good points, I agree! I added flush to the docs, so people using a search engine will find it for sure :relaxed: 
Should I rebase the commits into one?

Cheers,
Stefan

**Comment by djc** [comment]
No need to squash, we can easily do that when we merge.

**Review by bluejekyll — APPROVED** [review]
Looks good.

**Comment by bluejekyll** [comment]
I’ll squash the commits. Thanks for the PR!

**Pull request merged**
