### PR TITLE
Update to *ring* 0.16, webpki 0.21, Rustls 0.16, and tokio-rustls 0.10

### PR DESCRIPTION
**Pull request by briansmith**

### CODE REVIEW

**Comment by briansmith** [comment]
Note: The new dependencies in Cargo.lock look scary, but the ones from *ring* are all webassembly-specific and won't affect other platforms.

**Comment by briansmith** [comment]
Not sure what to make of this:
https://ci.appveyor.com/project/bluejekyll/trust-dns/builds/26611629/job/j9a2mnjra9kd78xd#L903

**Comment by bluejekyll** [comment]
AppVeyor sometimes has never ending tests. I still don’t know why. I’ll rerun, but it’s probably not an issue.

**Comment by bluejekyll** [comment]
Merging, thanks, @briansmith! I’ll try and prep a release tonight.

**Pull request merged**
