### PR TITLE
create default rules for justfile

### PR DESCRIPTION
**Pull request by bluejekyll**
This is the beginnings of replacing cargo-make with something simpler.

fixes: #1934

### CODE REVIEW

**Comment by bluejekyll** [comment]
Add certificate regeneration to justfile

**Comment by bluejekyll** [comment]
This has a dependency on https://github.com/pksunkara/cargo-workspaces/pull/98

**Comment by bluejekyll** [comment]
Ok, this moves everything over to `just` for all task automation. I think it's ready to be merged. It includes moving all CI to just as well. The new `cargo-workspaces` version was deployed that had the associated changes needed for ignoring crates in some of the test runs.

**Comment by bluejekyll** [comment]
hm, Cargo.lock updated, I'm not sure why. I should revert that.

**Comment by mokeyish** [comment]
Hi, It seems that you use `cargo-workspaces` to execute `build|test|...` on each crate. But cargo itself has the `--workpsace` option.

The document
https://doc.rust-lang.org/cargo/commands/cargo-test.html says

```
--workspace
Test all members in the workspace.
```

**Comment by bluejekyll** [comment]
> Hi, It seems that you use `cargo-workspaces` to execute `build|test|...` on each crate. But cargo itself has the `--workpsace` option.

Yes, I'm aware of that feature. The experience I've had is that when you use the workspace feature flag in Cargo you are limited by the feature sets you can enable or disable for each crate. In addition, there are times when certain builds enable things in ways that pass when compiling all, but fail when compiling individually. That's why I'm using a tool to individually test each of these. You can also see in this implementation that for some features, we ignore certain crates which don't support those. This should allow us to ensure that different things work across the range of use cases that people have for these crates.

**Comment by bluejekyll** [comment]
This is all ready to go, for anyone that wants to review.

**Review by djc — COMMENTED** [review]
I skimmed it, I guess it's fine.

**Review by djc — APPROVED** [review]

**Pull request merged**
