### PR TITLE
Optimized shutdown_gracefully()

### PR DESCRIPTION
**Pull request by caobug**
Doesn't move ownership, allowing the owner to determine the ServerFuture's lifecycle.

### CODE REVIEW

**Comment by djc** [comment]
As requested in #1977:

> and what your use case is (why does this complicate things).

**Comment by bluejekyll** [comment]
Would you mind updating the formatting? `cargo fmt` at the root should be enough to fix the cleanliness test.

@djc, not clear on your comment, are you not ok with this change? I like the simplification here...

**Comment by caobug** [comment]
@djc Hello,

I integrated trust-dns into the project and it looks like: Struct RunningContext->ServiceManager->ServerFuture.

After I call `shutdown_gracefully()`, I can't move the `ServiceManager` because the ownership has been moved.

I think I should control the life cycle myself.

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
Thanks, I think this is looking okay. If you rebase on top of current main (to get rid of the unrelated failure in CI) I can merge this (or @bluejekyll might get to it before me). If you rebase, please squash your changes together.

**Pull request merged**
