### PR TITLE
Typo fixes and https links upgrades

### PR DESCRIPTION
**Pull request by williamdes**

### CODE REVIEW

**Review by djc — APPROVED** [review]
Thanks!

**Comment by djc** [comment]
@bluejekyll I don't have permission to merge this due to the failing status check.

**Comment by williamdes** [comment]
> @bluejekyll I don't have permission to merge this due to the failing status check.

I rebased, last commit did not fail CI so this should now pass, I hope ^^

**Review by bluejekyll — APPROVED** [review]

**Comment by bluejekyll** [comment]
Thanks for the pr!

**Pull request merged**
